# Generated by Django 2.2.4 on 2021-06-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_auto_20210606_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderdesc',
            field=models.TextField(default=' '),
        ),
    ]
